save_path: exactot_01
cfm:
  matching_type: MyExactOptimal
  sigma: 0.000001
  alpha: 1
  sampler_method: exact
hidden_sizes:  [32, 64, 128, 256, 512, 512, 256, 256, 128, 64, 32]
lr: 1.e-5
epochs: 200
batch_size: 256
n_points: 400000
n_points_val: 400000
gaussian_points: 100
n_delta: 4
timesteps: 100