save_path: alphat_base_bump
cfm:
  matching_type: AlphaTTarget
  sigma: 0.000001
  alpha: 1
  sampler_method: default
hidden_sizes:  [32, 64, 128, 256, 512, 512, 256, 256, 128, 64, 32]
lr: 1.e-5
epochs: 200
batch_size: 256
n_points: 400000
n_points_val: 1000000
gaussian_points: 100
n_delta: 4
timesteps: 100